zenika-open-source/FAQ

src/scenes/Question/scenes/Edit/components/Tips/Tip.js
src/scenes/Question/scenes/Edit/components/Tips/index.js
src/scenes/Question/scenes/Edit/components/Tips/tips.json
src/scenes/Question/scenes/Edit/index.js

Show tips to write great questions

---

server/graphcool.yml
server/src/flags/clearOnAnswerUpdate.js
server/types.graphql
src/scenes/Question/scenes/Answer/index.js
src/scenes/Question/scenes/Answer/queries.js
src/scenes/Question/scenes/Edit/index.js
src/scenes/Question/scenes/Edit/queries.js
src/scenes/Question/scenes/Read/components/Flag/index.js
src/scenes/Question/scenes/Read/components/Meta/index.js
src/scenes/Question/scenes/Read/components/OptionsMenu/index.js
src/scenes/Question/scenes/Read/index.js
src/scenes/Question/scenes/Read/queries.js

Flag answers as outdated or incomplete

---

src/scenes/Home/components/ResultList/index.js

Scroll to top on page change

---

app.yaml
src/components/Input/Input.jsx
src/scenes/Home/components/Result/Result.jsx
src/scenes/NotFound/NotFound.jsx
src/scenes/Question/Question.jsx
src/scenes/Question/queries.js
src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Answer/queries.js
src/scenes/Question/scenes/Edit/Edit.jsx
src/scenes/Question/scenes/Edit/queries.js
src/scenes/Question/scenes/Read/Read.jsx
src/scenes/Question/scenes/Read/queries.js
src/services/routing.js

Fixes (#24)
Demo: https://next-dot-faq-zenika.appspot.com

:sparkles: Use UID in urls

---

README.md
server/algolia/synonyms.js
server/algolia/synonyms.json
server/package.json

Deploy synonyms (NDF <=> Note de frais) to Algolia using a JSON file for easy contributions

:sparkles: Algolia synonyms

---

src/components/Dropdown/DropdownItem.jsx

:bug: Fix dropdown link not triggering

---

src/scenes/Home/Home.jsx
src/scenes/Home/components/Searchbar/Searchbar.jsx

Not a problem when typing a question.
But when holding <kbd>Backspace</kbd> to erase a question it doesn't feel so smooth, should be better with the debounce.
@Errorname Feel free to change the debounce wait value, or even remove it.

Add a debounce on search field

---

src/components/Flags/Flag.jsx
src/scenes/Question/scenes/Read/Read.jsx

Adding duplicate flags

---

src/components/Authenticated/Authenticated.jsx
src/scenes/App/App.jsx
src/scenes/App/components/Navbar/Navbar.jsx
src/scenes/Auth/Callback.jsx
src/scenes/Auth/Login.jsx
src/services/auth.js

This PR changes the authentication workflow:
* When a user loads the application:
* If first time or new computer: show login page which redirects to Auth0 login page (3 clicks)
* Else: renew token in the background while showing a loader (0 clicks)
* While a user is authenticated:
* 5min before the end of its token validity: renew token in the background without showing a loader

Renew auth before end of token

---

src/components/Card/CardText.jsx
src/components/Input/Input.jsx
src/components/onCtrlEnter/index.js
src/components/onCtrlEnter/onCtrlEnter.jsx
src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Edit/Edit.jsx

Submit on ctrl+enter

---

server/graphcool.yml
server/src/random/queries.js
server/src/random/random.graphql
server/src/random/random.js
src/scenes/Question/Question.jsx
src/scenes/Question/queries.js
src/scenes/Question/scenes/Random/Random.jsx
src/scenes/Question/scenes/Random/index.js
src/scenes/Question/scenes/Random/queries.js

Going to /q/random will get you redirected to a random question.
You can also try with flags:
* /q/random/outdated
* /q/random/incomplete
* ...

Find random questions

---

src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Edit/Edit.jsx

Confirm leaving a page with inputs

---

package-lock.json
package.json
src/components/Dropdown/Dropdown.css
src/scenes/Question/scenes/Read/Read.jsx
src/scenes/Question/scenes/Read/components/Share/Share.css
src/scenes/Question/scenes/Read/components/Share/Share.jsx
src/scenes/Question/scenes/Read/components/Share/index.js

Share button on question page

---

src/components/Input/Input.css
src/components/Input/Input.jsx
src/scenes/App/components/Navbar/Navbar.css
src/scenes/App/components/Navbar/Navbar.jsx
src/scenes/Home/components/Searchbar/Searchbar.jsx
src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Answer/components/Sources/Sources.jsx

Implements:
* Hide "source links form" when creating / editing a response #47 
* Add a "report a bug" link #48
* I can reset the words searched in one clic. #49

Improve UX

---

.gitignore
README.md
docs/backing_services.md
docs/contributing.md
docs/deployment.md
docs/installation.md
server/algolia/synonyms.js
server/package.json
server/src/algolia/sync.js
src/services/search.js

This PR does the following:
* Refact documentation in multiple files (See new [README.md](https://github.com/Zenika/FAQ/blob/contributing/README.md))
* Show how to use local graphcool deployment
* Make Algolia optional when developing (with a stub)
* Make Mailgun optional when developing

Improving first-time contributing experience

---

src/scenes/NotFound/NotFound.jsx
src/scenes/Question/scenes/Edit/components/Tips/Tips.jsx
src/scenes/Question/scenes/Read/components/Share/Share.jsx

This PR fixes:
* #61 : The button on "Not Found" pages now redirects to Home
* #57 : The encoding is now respected when sharing to workplaces
* part of #59 : Duplicate tip is removed

Fix small UI mistakes

---

src/scenes/UserProfile/UserProfile.jsx
src/scenes/UserProfile/queries.js

Editable identity on profile page

---

server/graphcool.yml
server/src/flag/uniqueFlag.js
src/scenes/Question/scenes/Read/queries.js

Ensure unique flag of a certain type

---

docs/installation.md
docs/step_by_step.md
server/package.json

Remove unnecessary global dependencies

---

.circleci/config.yml
server/package-lock.json
server/src/answer/sources.js
server/src/answer/update.graphql
server/src/answer/update.js
server/src/question/tags.js
server/src/question/update.graphql
server/src/question/update.js
server/types.graphql
src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Answer/queries.js
src/scenes/Question/scenes/Edit/queries.js
src/scenes/Question/scenes/Read/Read.jsx
src/scenes/Question/scenes/Read/components/History/History.css
src/scenes/Question/scenes/Read/components/History/History.jsx
src/scenes/Question/scenes/Read/components/History/HistoryAction.jsx
src/scenes/Question/scenes/Read/components/History/HistoryActions.jsx
src/scenes/Question/scenes/Read/components/History/index.js
src/scenes/Question/scenes/Read/components/History/queries.js
src/scenes/Question/scenes/Read/queries.js
src/services/history.js
src/services/index.js

Add history to a question

---

src/components/Flags/Flag.jsx
src/components/Flags/Flags.css
src/components/Flags/Flags.jsx

:bug: Fix flags order

---

src/components/Tags/Tags.jsx

:bento: Add tags marketing and dt

---

server/algolia/settings.js

:wrench: Remove stopwords in searches

---

src/scenes/Question/scenes/Read/components/History/HistoryAction.jsx

:lipstick: Format history actions date based on elapsed time

---

src/components/Card/Card.css
src/scenes/App/components/Navbar/Navbar.css
src/scenes/Home/components/Searchbar/Searchbar.css
src/scenes/Question/scenes/Read/Read.jsx
src/scenes/Question/scenes/Read/components/History/History.css
src/styles/theme.css

:lipstick: Improve UX after reviews

---

package-lock.json
package.json
src/components/Flags/Flags.jsx
src/helpers/history.js
src/scenes/Home/components/Result/Result.jsx
src/scenes/Question/scenes/Read/components/Meta/Meta.jsx

[Issue #112 ]
There is a use of moment.fromNow() to get relative date, so I decided to use date-fns over reinventing the wheel.

Replace momentjs with date-fns

---

docs/step_by_step.md

`npm run deploy` requires the environment files so we need to create them first

:bug: Fix step by step

---

docs/integrations.md
server/prisma/datamodel.graphql
server/src/generated/prisma.graphql
server/src/index.js
server/src/middlewares/auth.js
server/src/schema.graphql
src/scenes/App/components/Navbar/components/UserMenu/queries.js
src/scenes/Auth/queries.js
src/scenes/UserProfile/queries.js

:sparkles: Public API integration

---

package-lock.json
package.json
server/package-lock.json
server/package.json
server/prisma/Dockerfile.clever-cloud
server/prisma/docker-compose.yml

:arrow_up: Update React-scripts and Prisma

---

server/package.json
src/helpers/serialize.js

:bug: Fix URL decoding

---

server/package-lock.json
server/package.json
server/src/instanciator.js

:arrow_up: Upgrade prisma-binding

---

server/src/resolvers/integrations/slack.js

Didn't try it locally. Can you make sure it works as expected? :)

:sparkles: Add question tags in Slack messages

---

server/prisma/datamodel.graphql
server/src/endpoints/configuration.js
server/src/generated/prisma.graphql
server/src/schema.graphql
src/scenes/App/components/Navbar/Navbar.jsx
src/scenes/Settings/Settings.css
src/scenes/Settings/Settings.jsx
src/scenes/Settings/queries.js
src/services/configuration.js

The admin can now change the title of the tenant 🎉

:sparkles: Change tenant title in settings

---

src/components/Flags/Flag.jsx

Different color for every flag

---

server/scripts/helpers.js

:bug: fix prisma scripts cannot find the prisma executable

---

server/src/resolvers/answer.js
server/src/resolvers/question.js
server/src/schema.graphql
src/scenes/Question/scenes/Answer/Answer.jsx
src/scenes/Question/scenes/Answer/queries.js
src/scenes/Question/scenes/Edit/Edit.jsx
src/scenes/Question/scenes/Edit/queries.js

:sparkles: Protect concurrent edition of a question

---

server/prisma/datamodel.graphql
server/src/generated/prisma.graphql

:card_file_box: enableWorkplaceSharing is now required

---

server/prisma/datamodel.graphql
server/src/generated/prisma.graphql
server/src/index.js
server/src/middlewares/auth.js
server/src/middlewares/configuration.js
server/src/resolvers/configuration.js
server/src/schema.graphql
src/scenes/Settings/Settings.css
src/scenes/Settings/Settings.jsx
src/scenes/Settings/Settings.scss
src/scenes/Settings/helpers.js
src/scenes/Settings/queries.js

:sparkles: Configuration for domain's email authorization

---

server/src/index.js
server/src/middlewares/first-user.js
server/src/middlewares/index.js
server/src/resolvers/user.js

This PR is about the issue #157
It allows to make the first user admin.

:sparkles: introduce first user as admin feature

---

client/src/helpers/serialize.js

:bug: Fix percent sign in search

---

client/src/services/markdown.js

:bug: Correctly parse highlights links

---

client/src/scenes/App/components/Navbar/Navbar.jsx
client/src/services/markdown.js

:bug: Fix em in links

---

client/src/components/Flags/Flags.css

:bug: Small UI fix for tags label

---

client/package-lock.json
client/package.json
client/public/robot.txt
client/src/contexts/Configuration/ConfigurationProvider.jsx
client/src/scenes/Settings/Settings.jsx
server/package-lock.json
server/package.json

- I have added husky and pretty-quick as a dev dependency to achieve the objective referenced in #212 
- Tested it by adding a few spaces to a bunch of files before commiting

:sparkles: Added Precommit script to run prettify on staged files

---

client/src/scenes/App/components/Footer/Footer.jsx
client/src/scenes/App/components/Footer/Footer.scss
client/src/scenes/App/components/Navbar/Navbar.jsx
client/src/scenes/App/components/Navbar/components/UserMenu/UserMenu.jsx
client/src/scenes/UserProfile/UserProfile.jsx
client/src/styles/layout.css

En attente de la création de l'alias mail contact@faq.team

:children_crossing: Add contact email in footer

---

server/prisma/datamodel.graphql
server/src/generated/prisma.graphql

:building_construction: Refacto tags (part2)

---

client/src/components/TagPicker/TagPicker.jsx
client/src/components/Tags/Tags.jsx
client/src/components/Tags/Tags.mdx
client/src/scenes/Home/Home.jsx
client/src/scenes/Home/components/Searchbar/Searchbar.jsx
client/src/scenes/Home/queries.js
client/src/scenes/Question/queries.js
client/src/scenes/Question/scenes/Edit/Edit.jsx
client/src/scenes/Question/scenes/Edit/queries.js
server/prisma/datamodel.graphql
server/src/generated/prisma.graphql
server/src/integrations/algolia.js
server/src/integrations/slack.js
server/src/resolvers/question.js
server/src/resolvers/random.js

:building_construction: Refacto tags (part3)

---

server/prisma/datamodel.graphql

:building_construction: Refacto tags (part4 and last)

---

client/src/scenes/Question/scenes/Read/components/Views/Views.jsx

:pencil: Correct a typo when there is only one view

---

.github/CODE_OF_CONDUCT.md

:pencil: Add code of conduct

---

client/package-lock.json
client/package.json
client/src/scenes/Settings/Settings.jsx
client/src/scenes/Settings/scenes/General.jsx
client/src/scenes/Settings/scenes/Integrations.jsx
client/src/scenes/Settings/scenes/Synonyms.jsx
client/src/scenes/Settings/scenes/Tags.jsx
client/src/scenes/Settings/scenes/index.js
server/scripts/prisma_new_service/index.js

- Split Settings.jsx in more files
- Upgrade node-sass for macos compatibility
- Fix tags when new_service script is run

:building_construction: Mini-refacto settings

---

client/src/scenes/Home/Home.jsx

I realized on the website that each time I was typing in the input, there were around 3 requests sent.
My PR aims to fix this by sending the request only after 200ms once the user stopped typing.

:bug: Extract debounce callback in order to be able to cancel it

---

.circleci/config.yml

- Use new CircleCI base images
- Reuse executors

👷‍♂️ upgrade ci

---

client/src/helpers/safeFetch.js
server/src/endpoints/configuration.js

Ajout d'un message d'erreur dans le configuration endpoint afin d'expliquer la cause potentielle d'une erreur

:goal_net: add an explanation for the error caused by the absence of configuration

---

server/src/middlewares/configuration.js

Converted refreshConfiguration function from then catch to async / await

:recycle: convert refreshConfiguration to async / await

---

server/src/helpers/index.js
server/src/integrations/mailgun/answer/index.js
server/src/integrations/slack.js

This might be the cause of production crashes.

♻️ avoid circular dependency

---

client/src/helpers/translation.js
client/src/scenes/Question/scenes/Read/Read.jsx
e2e/client.test.js
server/src/middlewares/auth.js
server/src/multiTenant.js

This PR makes the question screen display the content in the language of the navigator, if the content is available in this language.

✨ automatically display content in navigator language if available

---

client/src/scenes/Question/scenes/Random/Random.container.js
client/src/scenes/Question/scenes/Read/components/History/HistoryActions.container.js
client/src/services/routing.js

This pr fix a crash when trying to access the history of a question because the containers was still using react router v4 props and not react router v6 hooks

:ambulance: fix crash when trying to see the history of a question

---

client/src/components/Flags/Flag.jsx
server/src/resolvers/answer.js

Automatically create a flag when an answer has different versions (the certified version and the latest version)

:sparkles: add flag when an answer has multiple versions

---

client/src/scenes/Home/components/Result/Result.jsx
client/src/scenes/Home/queries.js
client/src/scenes/Question/scenes/Read/Read.jsx
e2e/client.test.js

:sparkles: add automatic translation of question and answer on list view

---

client/src/index.css

Add margin to answers paragraphs
