package.json, src/components/Card/Card.css, src/scenes/App/App.jsx, src/scenes/App/components/Navbar/Navbar.jsx, src/scenes/UserProfile/UserProfile.jsx, src/scenes/UserProfile/index.js, src/scenes/UserProfile/queries.js
A first step towards GDPR compliancy (see #36).
=> Read-only profile page

src/scenes/Auth/Login.jsx
Auth0 limits the renewal of passed token to around 2 days. After that, login is required.
In this case, we shouldn't show an error.
Fixes #66
=> :bug: Fix login error message

server/src/answer/sources.js
Every sources was either added, updated or deleted. This had no impact until history came along. Now this shows: "edited question and updated X sources" even when the user doesn't change any sources.
This PR fixes this in order to only update a source when needed.
=> :bug: Fix sources that should not have been updated

server/prisma/migration_graphcool/README.md, server/prisma/resync_algolia/README.md, server/prisma/resync_algolia/index.js, server/src/resolvers/answer.js
The "unanswered" flags were not stored into the DB in graphcool, but implied by the absence of answer. But they are now stored in Prisma. 
The migration script forgot to create these flags in the new DB for previously created questions.
Issue #96 encountered a bug because the graphql resolver assumed there was a "unanswered" flag in the DB.
This has been fixed in the production database. And this PR add a notes in the readme of the migration script.
=> :memo: Document a missing step in the migration

package-lock.json, package.json, src/scenes/Question/scenes/Answer/components/Source/Source.jsx, src/services/markdown.js
[issue #118]
`emoji-dictionary` was using `emojilib` and a bunch of other packages. However, `emojilib` has a `simplemap.json` file which is enough for our case.
This changes the bundle size from 983.6k minified (2.0M raw) to 819.4k minified (1.8M raw) around 15% improvement!
=> :heavy_minus_sign: Replace emoji-dictionary with emojilib

server/src/resolvers/answer.js, src/components/AlertStack/Alert.jsx
Partially covers #127 
If multiple users attempts to create an answer (aka: answer for the first time) a question, the subsequent users will now see an error alert. They won't lose what they wrote.
=> :children_crossing: Protect concurrent creation of an answer

src/scenes/Question/scenes/Read/components/Share/Share.jsx, src/services/routing.js
Implements #162 
The new share URL will look like: `https://zenika.faq.team/q/cjragybxz0dz90803yjvrsn25`.
When a user access this URL, he will be redirected to the long URL: `https://zenika.faq.team/q/what-should-i-do-after-i've-made-an-open-source-contribution-cjragybxz0dz90803yjvrsn25`
=> :sparkles: Minified share url

.circleci/config.yml, package-lock.json, package.json, server/.eslintrc, server/package-lock.json, server/package.json, server/src/directives/admin.js, server/src/multiTenant.js, src/helpers/onListChange.js, src/helpers/serialize.js
My original goal was to parallelize the CI jobs to gain speed however it turned into something else.
The speed gain is next to nothing because the build was already very fast thanks to it entirely running in one container (no network transfers vs multiple containers). However, it's not slower, and some jobs happen earlier on in the workflow. In particular, linting the server code happens much sooner, tightening the feedback loop. Also, GitHub is able to report more precise feedback on failed builds because it can pinpoint the task that failed.
Interestingly this task made me find problems with the linting facilities. First, the server-side package.json was missing required dependencies for linting, that it would find in the client-side node_modules. If those were not there linting could …
=> Parallelized CI

server/scripts/helpers.js, server/scripts/prisma_new_service/index.js
#167 introduced a bug when it switched from execFile to exec without changing up the arguments. execFile takes a file, then command arguments, then options. exec only take 2 arguments: the command and the options. This made scripts ignore the command arguments and options. This did not raise an error because the scripts were running prisma without any argument, so prisma would display the help and exit normally, and the script would assume that everything when fine.
=> :bug: fix prisma scripts not actually running commands

server/src/endpoints/configuration.js, server/src/middlewares/configuration.js, src/services/configuration.js
When an error occurred while retrieving configuration, the client would show a infinite loading screen. This change makes a crude error appear instead.
There's an optional refactoring commit in there, you might no want it.
=> :children_crossing: handle errors when retrieving configuration

LICENSE.md
Following discussion with Zenika Open Source advocates, we chose to use the Apache 2 license instead of the MIT license
=> :memo: Change license to Apache 2

client/src/components/Input/MarkdownEditor/MarkdownEditor.jsx, client/src/services/markdown.js
Fixes #203 
There was 2 problems:
1. We weren't using the same methods when rendering markdown in the editor and rendering markdown in the rest of the app.
2. Our way of detecting a markdown link was flawed. It was working on the assumption that there would be a whitespace after the markdown link.
Those two problems are now fixed.
Note: This bug is yet another example on why we need to add tests to this application (See #138)
=> :bug: Fix markdown link detection

README.md
The license was still MIT in README.md.
=> :pencil: Set the right license name in README.md

client/package-lock.json, client/package.json
This makes this app installable and buildable using Node.js 12, which require node-sass 4.12+.
While I was working on #238, `npm install` failed because the node-sass post-install script encountered a compilation problem. This is quite a common problem with node-sass so I checked the versions. I found I was running Node.js 12.4 and trying to compile node-sass 4.11. The [node-sass documentation](https://www.npmjs.com/package/node-sass) shows that this is an incompatible combination. So I proceeded to upgrade to node-sass 4.12. The [changelog](https://github.com/sass/node-sass/releases/tag/v4.12.0) for 4.12 indicates this release adds support for Node.js 12 and nothing else, so it should be free of any breaking change. I also moved the dependency to `devDependency`, I hope that's alright.
=> :arrow_up: upgrade node-sass

server/src/resolvers/answer.js
While I was working on #238, I made a mistake in the GraphQL query located [here](https://github.com/zenika-open-source/FAQ/blob/master/server/src/resolvers/answer.js#L32-L39). More precisely, I asked for a field that did not exist. I got an error in my terminal, however, it was not about my mistake, it said `Could not read property includes of undefined`. It turns out the code that handles errors for this query is expecting the error to always have a field `message` that is an array, and crashes if it does not.
This PR makes the code verify those assumptions, so that any other type error can bubble-up correctly.
=> :bug: fix crash in case of prisma error when answering

server/src/resolvers/answer.js
Thank you for maintaining FAQ!
This PR's goal is to fix #230 as simply as possible.
According to the Prisma GraphQL schema, a node might not have a question attached, therefore I might need to check for that in my condition (ie `answer.node.question && answer.node.question.user.id !== answer.user.id`). However I fail to see a case where an answer would be given for a node that has no question. What do you think?
=> :sparkles: disable answer email notification if the answerer is the asker

CONTRIBUTING.md
=> 📝 Ajout du CONTRIBUTING.md

server/src/middlewares/configuration.js
Message d'erreur : ERR_HTTP_HEADERS_SENT
Cause de l'erreur : oubli de l'utilisation de la commande 'npm run new_service' à l'étape 6 du guide d'installation
=> :bug: fix double server response when no configuration

.circleci/config.yml, server/scripts/helpers.js
- Add `prisma deploy` to the deploy pipeline
- Add correct env var values when building the client
- Require e2e tests to pass before deploying
=> 💚 fix deployment

.circleci/config.yml, client/package.json, client/src/helpers/safeFetch.js, client/src/services/apollo.js
Leverages the proxy feature from create-react-app instead of relying of required env vars and CORS for API requests.
=> 🛠️ leverage front-end server proxy

.circleci/config.yml
Add a parameter to the CircleCI pipeline that controls if `prisma deploy` should be run with the `--force` option. This can be useful when a data model migration is destructive.
=> 👷 add ci parameter to force prisma deployment

server/src/index.js
Vite changed the folder of built assets (CSS and JS files) from `static` to `assets` (see #346). However the production server treated `static` specially as a folder where it should not serve `index.html`. As a result, the server served `index.html` for all files located in `assets`, and assets could not be served in production. This fix adds `assets` to the list of files and folders that are treated specially by the server (in place of `static`).
=> 🚑 fix static asset serving in production

client/package-lock.json, client/package.json, client/src/components/Flags/Flag.jsx, client/src/components/Flags/Flags.jsx, client/src/helpers/history.js, client/src/scenes/App/App.jsx, client/src/scenes/Question/Question.container.js, client/src/scenes/Question/queries.js, client/src/scenes/Question/scenes/Read/Read.jsx, client/src/scenes/Question/scenes/Read/components/Meta/Meta.jsx, client/src/scenes/Settings/helpers.js, e2e/client.test.js, server/prisma/datamodel.graphql, server/src/generated/prisma.graphql, server/src/helpers/certified.js, server/src/resolvers/answer.js, server/src/resolvers/flag.js
This ensures that the latest certified answer is always accessible, even after the answer has been modified.
Also:
- Adds a confirm modal when editing a certified answer
- Adds the date of certification to the Certified flag
- Upgrade date-fns
- Fixes Algolia synonyms in some cases
=> :sparkles: Save and show the certified version of an answer
